title: Clark Rabe
logo: <img src="images/me.jpg?raw=true"/>
description:
  Bachelors in Computer Science
  <br><br>
  Focus on UX/UI
  <br><br>
  <a href="https://www.linkedin.com/in/clark-rabe-130ab9154/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
