title: Clark Rabe
#<img src="images/ME.jpg?raw=true"/>
<br>
description: 
  Bachelors in Computer Science
  <br><br>
  Focus on UX/UI
  <br><br>
  <a href="https://www.linkedin.com/in/clark-rabe-130ab9154/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
