title: Clark Rabe
logo: "/images/ME.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<br>
  Bachelors in Computer Science
  <br><br>
  Focus on UX/UI
  <br><br>
  <a href="https://www.linkedin.com/in/clark-rabe-130ab9154/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
