title: Clark Rabe
logo: "/images/me.jpg?raw=true"
description:
  <img src= "/images/me.jpg?raw=true">
  <br>
  Bachelors of Computer Science
  <br>
  UX/UI Certificate
  <br>
  Eastern Washington Univeristy
  <br><br>
  <font color="#63a52a">Email clarkrabe@gmail.com</font>
  <br>
  <a href="https://www.linkedin.com/in/clark-rabe-130ab9154/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-time-machine
